import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'CF258A CF258X 58X 59X 76A',
    description: 'High-quality black toner for crisp, professional documents. Perfect for everyday printing.',
    price: 10400,
    imageId: 'toner-1',
    specifications: { color: 'Black', yield: 'Approx. 2,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_002',
    name: 'CF410A CF411A CF412A CF413A 410A',
    description: 'Vibrant color toner set that delivers brilliant color prints and consistency.',
    price: 11700,
    imageId: 'toner-2',
    specifications: { color: 'CMYK', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_003',
    name: 'W1105A W1106A W1107A 105A 106A 107A',
    description: 'Rich black toner for eye-catching images and graphics.',
    price: 11700,
    imageId: 'toner-3',
    specifications: { color: 'Black', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_004',
    name: 'Universal-CE285A CB436A CB435A CE278A CRG-128',
    description: 'Bright black toner for vivid color and sharp details.',
    price: 11700,
    imageId: 'toner-4',
    specifications: { color: 'Black', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_005',
    name: 'Universal-CE505A 05A CF280A 80A CRG-319',
    description: 'High-yield black toner for high-volume printing. More pages, less hassle.',
    price: 16900,
    imageId: 'toner-5',
    specifications: { color: 'Black', yield: 'Approx. 5,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_006',
    name: 'Universal-CB435A 35A CE285A 85A CB436A 36A',
    description: 'Get our reliable black toner in one convenient value pack.',
    price: 42900,
    imageId: 'toner-6',
    specifications: { color: 'Black', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_007',
    name: 'MLT-D111S',
    description: 'Compatible black toner for various laser printers.',
    price: 9100,
    imageId: 'toner-7',
    specifications: { color: 'Black', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_008',
    name: 'TN-2410 TN-2420 DR-2425',
    description: 'Genuine OEM black toner for guaranteed compatibility and quality.',
    price: 13000,
    imageId: 'toner-8',
    specifications: { color: 'Black', yield: 'Approx. 1,600 pages', technology: 'Laser' },
  },
  {
    id: 'prod_009',
    name: 'Universal-Q2612A 12A FX-9 FX-10 CRG-103',
    description: 'A standard black toner for your daily printing needs.',
    price: 10400,
    imageId: 'toner-9',
    specifications: { color: 'Black', yield: 'Approx. 2,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_010',
    name: 'CF279A 79A',
    description: 'Crisp and clear prints with this reliable black toner.',
    price: 11000,
    imageId: 'toner-10',
    specifications: { color: 'Black', yield: 'Approx. 2,200 pages', technology: 'Laser' },
  },
  {
    id: 'prod_011',
    name: 'Universal - CE310A CE311A CE312A CE313A',
    description: 'Cost-effective toner for high-quality printing.',
    price: 9800,
    imageId: 'toner-11',
    specifications: { color: 'Black', yield: 'Approx. 1,800 pages', technology: 'Laser' },
  },
  {
    id: 'prod_012',
    name: 'CF217A 17A',
    description: 'Long-lasting toner for consistent performance.',
    price: 12500,
    imageId: 'toner-12',
    specifications: { color: 'Black', yield: 'Approx. 3,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_013',
    name: 'Asta Color Toner 013',
    description: 'Standard yield color toner for everyday documents.',
    price: 12000,
    imageId: 'toner-13',
    specifications: { color: 'Color', yield: 'Approx. 1,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_014',
    name: 'Asta Black Toner 014',
    description: 'Economical black toner for budget-friendly printing.',
    price: 8500,
    imageId: 'toner-14',
    specifications: { color: 'Black', yield: 'Approx. 1,200 pages', technology: 'Laser' },
  },
  {
    id: 'prod_015',
    name: 'Asta Color Toner 015',
    description: 'High-quality color toner for vibrant presentations.',
    price: 14000,
    imageId: 'toner-15',
    specifications: { color: 'Color', yield: 'Approx. 1,800 pages', technology: 'Laser' },
  },
  {
    id: 'prod_016',
    name: 'Asta Black Toner 016',
    description: 'A black toner for sharp, professional text.',
    price: 9900,
    imageId: 'toner-16',
    specifications: { color: 'Black', yield: 'Approx. 1,600 pages', technology: 'Laser' },
  },
  {
    id: 'prod_017',
    name: 'Asta Color Toner 017',
    description: 'Produces brilliant, high-resolution color images.',
    price: 15500,
    imageId: 'toner-17',
    specifications: { color: 'Color', yield: 'Approx. 2,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_018',
    name: 'Asta Black Toner 018',
    description: 'High-capacity black toner for large volume printing.',
    price: 18000,
    imageId: 'toner-18',
    specifications: { color: 'Black', yield: 'Approx. 6,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_019',
    name: 'Asta Color Toner 019',
    description: 'Reliable color toner for consistent print quality.',
    price: 13200,
    imageId: 'toner-19',
    specifications: { color: 'Color', yield: 'Approx. 1,400 pages', technology: 'Laser' },
  },
  {
    id: 'prod_020',
    name: 'Asta Black Toner 020',
    description: 'An affordable black toner for all your printing needs.',
    price: 8900,
    imageId: 'toner-20',
    specifications: { color: 'Black', yield: 'Approx. 1,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_021',
    name: 'Asta Color Toner 021',
    description: 'Genuine color toner for superior performance.',
    price: 14800,
    imageId: 'toner-21',
    specifications: { color: 'Color', yield: 'Approx. 1,900 pages', technology: 'Laser' },
  },
  {
    id: 'prod_022',
    name: 'Asta Black Toner 022',
    description: 'Consistent and reliable black prints from start to finish.',
    price: 11200,
    imageId: 'toner-22',
    specifications: { color: 'Black', yield: 'Approx. 2,100 pages', technology: 'Laser' },
  },
  {
    id: 'prod_023',
    name: 'Asta Color Toner 023',
    description: 'Bright and vivid color output for professional documents.',
    price: 16000,
    imageId: 'toner-23',
    specifications: { color: 'Color', yield: 'Approx. 2,200 pages', technology: 'Laser' },
  },
  {
    id: 'prod_024',
    name: 'Asta Black Toner 024',
    description: 'This toner offers exceptional value and performance.',
    price: 10500,
    imageId: 'toner-24',
    specifications: { color: 'Black', yield: 'Approx. 1,800 pages', technology: 'Laser' },
  },
  {
    id: 'prod_025',
    name: 'Asta Color Toner 025',
    description: 'Extended yield color toner for demanding print jobs.',
    price: 19000,
    imageId: 'toner-25',
    specifications: { color: 'Color', yield: 'Approx. 3,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_026',
    name: 'Asta Black Toner 026',
    description: 'Precision engineered for high-quality results.',
    price: 12800,
    imageId: 'toner-26',
    specifications: { color: 'Black', yield: 'Approx. 2,800 pages', technology: 'Laser' },
  },
  {
    id: 'prod_027',
    name: 'Asta Color Toner 027',
    description: 'Long-lasting color toner for vibrant, fade-resistant prints.',
    price: 17500,
    imageId: 'toner-27',
    specifications: { color: 'Color', yield: 'Approx. 2,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_028',
    name: 'Asta Black Toner 028',
    description: 'Designed for optimal performance and reliability.',
    price: 13500,
    imageId: 'toner-28',
    specifications: { color: 'Black', yield: 'Approx. 3,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_029',
    name: 'Asta Color Toner 029',
    description: 'Perfect for printing colorful marketing materials.',
    price: 14500,
    imageId: 'toner-29',
    specifications: { color: 'Color', yield: 'Approx. 1,700 pages', technology: 'Laser' },
  },
  {
    id: 'prod_030',
    name: 'Asta Black Toner 030',
    description: 'Professional quality black toner for business documents.',
    price: 11800,
    imageId: 'toner-30',
    specifications: { color: 'Black', yield: 'Approx. 2,400 pages', technology: 'Laser' },
  },
  {
    id: 'prod_031',
    name: 'Asta Black Toner 031',
    description: 'Premium toner for monochrome printing.',
    price: 13000,
    imageId: 'toner-31',
    specifications: { color: 'Black', yield: 'Approx. 2,600 pages', technology: 'Laser' },
  },
  {
    id: 'prod_032',
    name: 'Asta Color Toner 032',
    description: 'High-performance color toner for photo-quality prints.',
    price: 18500,
    imageId: 'toner-32',
    specifications: { color: 'Color', yield: 'Approx. 3,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_033',
    name: 'Asta Black Toner 033',
    description: 'A reliable choice for your monochrome laser printer.',
    price: 9500,
    imageId: 'toner-33',
    specifications: { color: 'Black', yield: 'Approx. 1,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_034',
    name: 'Asta Color Toner 034',
    description: 'This color toner pack offers great value for money.',
    price: 35000,
    imageId: 'toner-34',
    specifications: { color: 'Color', yield: 'Approx. 1,500 pages per cartridge', technology: 'Laser' },
  },
  {
    id: 'prod_035',
    name: 'Asta Black Toner 035',
    description: 'Ultra high-yield toner for maximum printing efficiency.',
    price: 25000,
    imageId: 'toner-35',
    specifications: { color: 'Black', yield: 'Approx. 10,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_036',
    name: 'Asta Color Toner 036',
    description: 'Value pack of color toners for high-volume color printing.',
    price: 45000,
    imageId: 'toner-36',
    specifications: { color: 'Color', yield: 'Approx. 2,200 pages per cartridge', technology: 'Laser' },
  },
  {
    id: 'prod_037',
    name: 'Asta Black Toner 037',
    description: 'Get sharp text and crisp graphics with every print.',
    price: 12300,
    imageId: 'toner-37',
    specifications: { color: 'Black', yield: 'Approx. 2,300 pages', technology: 'Laser' },
  },
  {
    id: 'prod_038',
    name: 'Asta Color Toner 038',
    description: 'This toner is perfect for creating vibrant flyers and brochures.',
    price: 16500,
    imageId: 'toner-38',
    specifications: { color: 'Color', yield: 'Approx. 2,400 pages', technology: 'Laser' },
  },
  {
    id: 'prod_039',
    name: 'Asta Black Toner 039',
    description: 'An easy-to-install toner cartridge for your convenience.',
    price: 10200,
    imageId: 'toner-39',
    specifications: { color: 'Black', yield: 'Approx. 1,900 pages', technology: 'Laser' },
  },
  {
    id: 'prod_040',
    name: 'Asta Color Toner 040',
    description: 'Enjoy consistent, print-shop quality results.',
    price: 17000,
    imageId: 'toner-40',
    specifications: { color: 'Color', yield: 'Approx. 2,600 pages', technology: 'Laser' },
  },
  {
    id: 'prod_041',
    name: 'Asta Black Toner 041',
    description: 'Specially formulated toner for uniform print coverage.',
    price: 11500,
    imageId: 'toner-41',
    specifications: { color: 'Black', yield: 'Approx. 2,000 pages', technology: 'Laser' },
  },
  {
    id: 'prod_042',
    name: 'Asta Color Toner 042',
    description: 'This toner delivers impressive color accuracy and detail.',
    price: 19500,
    imageId: 'toner-42',
    specifications: { color: 'Color', yield: 'Approx. 3,200 pages', technology: 'Laser' },
  },
  {
    id: 'prod_043',
    name: 'Asta Black Toner 043',
    description: 'High-performance toner for professional documents.',
    price: 14000,
    imageId: 'toner-43',
    specifications: { color: 'Black', yield: 'Approx. 3,500 pages', technology: 'Laser' },
  },
  {
    id: 'prod_044',
    name: 'Asta Color Toner 044',
    description: 'Produces sharp, vibrant color prints from the first page to the last.',
    price: 15800,
    imageId: 'toner-44',
    specifications: { color: 'Color', yield: 'Approx. 2,100 pages', technology: 'Laser' },
  }
];

export function getProductById(id: string): Product | undefined {
  return products.find((product) => product.id === id);
}

// Mock order data
export const sampleOrder = {
  id: 'ORD12345',
  date: '2024-05-20',
  status: 'Shipped',
  trackingNumber: '1Z9999W99999999999',
  items: [
    { ...products[0], quantity: 1 },
    { ...products[4], quantity: 2 },
  ],
  total: 339.97,
  shippingAddress: {
    name: 'Jane Doe',
    street: '123 Tech Lane',
    city: 'Innovation City',
    state: 'CA',
    zip: '90210',
  },
  billingAddress: {
    name: 'Jane Doe',
    street: '123 Tech Lane',
    city: 'Innovation City',
    state: 'CA',
    zip: '90210',
  },
};
